#Here we can put all of our web sites.
sites = [
    ["YouTube", "https://www.youtube.com"],
    ["Wikipedia", "https://www.wikipedia.org"],
    ["Google", "https://www.google.com"],
    ["Google Traductor", "https://translate.google.com"],
    ["Facebook", "https://www.facebook.com"],
    ["Twitter", "https://twitter.com"],
    ["Instagram", "https://www.instagram.com"],
    ["LinkedIn", "https://www.linkedin.com"],
    ["Amazon", "https://www.amazon.com"],
    ["Netflix", "https://www.netflix.com"],
    ["Reddit", "https://www.reddit.com"],
    ["GitHub", "https://github.com"],
    ["Stack Overflow", "https://stackoverflow.com"],
    ["Ebay", "https://www.ebay.com"],
    ["Microsoft", "https://www.microsoft.com"],
    ["Apple", "https://www.apple.com"],
    ["Adobe", "https://www.adobe.com"],
    ["CNN", "https://edition.cnn.com"],
    ["BBC", "https://www.bbc.com"],
    ["The New York Times", "https://www.nytimes.com"],
]

#This is how SUS-Ai refers to us.
welcome = [
    "¡Bienvenido, señor!",
    "Saludos, señor.",
    "Estoy a su servicio señor.",
    "Bienvenido de nuevo señor.",
    "¿En qué puedo ayudarle hoy señor?",
    "Es un placer atenderle señor.",
    "¡Hola señor!",
    "¿Cómo puedo asistirle hoy señor?",
    "Estoy listo para ayudar señor.",
    "Bienvenido a su asistente virtual señor.",
    "¿En qué puedo asistirle señor?",
    "Hola señor. ¿En qué puedo colaborar?",
    "Su asistente virtual a su disposición señor.",
    "Saludos señor. ¿Cómo puedo ayudarle?",
    "¿Qué necesita hoy señor?",
    "Bienvenido de nuevo señor. ¿En qué puedo ayudarle?",
    "Su asistente virtual está listo señor.",
    "Un placer saludarle señor.",
    "¿En qué puedo hacer su día mejor señor?",
    "¡Hola señor! ¿En qué puedo asistirle?",
    "Estoy aquí para ayudarle señor.",
    "Saludos señor. ¿Cómo puedo ser útil hoy?",
    "¿Qué puedo hacer por usted hoy señor?",
    "Estoy a su disposición señor.",
    "Bienvenido. ¿En qué puedo ayudarle señor?",
    "Es un honor asistirle señor.",
    "Estoy listo para sus instrucciones señor.",
    "¡Hola señor! ¿En qué puedo colaborar?",
    "Su asistente virtual está a su servicio señor.",
    "Saludos, señor. ¿Qué puedo hacer para usted hoy?",
    "¿En qué puedo asistirle señor?",
    "Bienvenido de nuevo señor. ¿En qué puedo ayudarle?",
    "Su asistente virtual está preparado señor.",
    "Un placer estar a su servicio señor.",
    "¿Qué puedo hacer para que su día sea mejor, señor?",
    "¡Hola señor! ¿En qué puedo asistirle hoy?",
    "Estoy aquí para ayudarle en todo lo que necesite, señor.",
    "Saludos señor. ¿Cómo puedo ser de utilidad hoy?",
    "Estoy a su disposición señor. ¿En qué puedo ayudarle?",
    "Estoy listo para recibir sus instrucciones señor.",
    "¡Hola señor! ¿En qué puedo colaborar?",
    "Su asistente virtual está a su servicio señor. ¿En qué puedo ayudarle?",
    "Saludos señor. ¿Cómo puedo facilitar su día?",
    "¿En qué puedo asistirle señor? Estoy listo para ayudar.",
    "Bienvenido de nuevo señor. ¿Qué puedo hacer por usted?",
    "Su asistente virtual está preparado y esperando sus órdenes señor.",
    "Un placer saludarle señor. ¿Qué puedo hacer por usted?",
]

#This is how we should need to write the numbers that we want to add.
numbers = [["+593nnnnnnnnn","mica"],
           ["+593nnnnnnnnn", "mamita"],
           ["+52nnnnnnnnnn", "julián"],
           ["+52nnnnnnnnnn", "chava"],
           ["+52nnnnnnnnnn", "karina"],
           ["+593nnnnnnnnn", "came"],
           ["+593nnnnnnnnn", "papi"]]
